### ISSUE TITLE
Problem with migrations folders

### ISSUE THREAD

**Issue by kryskool** [OCA/product-attribute#10]
Hi

I see a problem with the folder migration, see the screenshot
I think the problem come from Launchpad Migrations

![Github View](https://cloud.githubusercontent.com/assets/337842/3977724/abd7f37e-283d-11e4-92ee-f9c86b59b296.png)

Regards,

**Comment by pedrobaeza** [comment]
Yeah, it can be. In OCB happened something similar. The solution is to make a PR solving the problem.

Regards.

**Comment by bwrsandman** [comment]
That's not a problem, github just updated their api.
It shows that way because migrations only has 7.0.0.2 as a folder inside, it concatenates them in the interface, that is all.

You can still visit:
- https://github.com/OCA/product-attribute/tree/7.0/product_custom_attributes/migrations
- https://github.com/OCA/product-attribute/tree/7.0/product_custom_attributes/migrations/7.0.0.2
