### ISSUE TITLE
[14.0]Product multi image failed on variants

### ISSUE THREAD

**Issue by flotho** [OCA/product-attribute#1097]
Trying to add multi image on product.product cause the following error :

![image](https://user-images.githubusercontent.com/1043935/176908232-4e91b5ca-ab6a-4bce-819f-c16ee1c77432.png)

## Module

product_multi_image

## Describe the bug

The issue is thrown on this line https://github.com/OCA/product-attribute/blob/14.0/product_multi_image/models/product_product.py#L34 so mostly it could also come from https://github.com/OCA/server-tools/blob/14.0/base_multi_image/models/owner.py#L59
Looks like Odoo is trying to save something that is not a base64 binary :
![image](https://user-images.githubusercontent.com/1043935/176908777-87ebb4e2-c7bc-4797-aace-e4e7f46082f6.png)

## To Reproduce
**Affected versions**: 14.0 up to date

1. install the module
2. add an image on a product.product (whatever the storage)
3. try to save the record

**Expected behavior**
expecting image to be save like for product.template

**Additional context**
adding an image on a product template works like a charm

**Comment by flotho** [comment]
The image is created and avialble via the dedicated menu in settings but not available via the produt.product menu

**Comment by saxomanu** [comment]
Hi! I have the same problem.
I patch by replace https://github.com/OCA/product-attribute/blob/14.0/product_multi_image/models
![image](https://user-images.githubusercontent.com/33661727/176914194-2e69d88b-b85d-48d6-894a-310d0fa4b0a2.png)

by
![image](https://user-images.githubusercontent.com/33661727/176914125-438804ab-e3c3-4fd4-9acf-7c1f585887d8.png)

In fact, with log, product.image_ids[0].image_main not return raw content, but something like b'34 KB'
 (size of the raw content).
I think it's ORM problem because image_main have a good content.

**Comment by flotho** [comment]
Thanks @saxomanu , what's your point of view on this line https://github.com/OCA/product-attribute/blob/14.0/product_multi_image/models/product_product.py#L69
I observed the following situation, when saving the product, here we have an image https://github.com/OCA/product-attribute/blob/14.0/product_multi_image/models/product_product.py#L50 created. AFAICS, the test `False if len(product.image_ids) < 1 else product.image_ids[0].image_main` should return at least the image because it's bound to the product.product a few lines before on L68 but the test still return False.
Maybe there's a cache issue there ?

**Comment by flotho** [comment]
Hi @hailangvn , already have this issue ?

**Comment by hailangvn** [comment]
Good day @flotho, thanks for logging the issue. Sorry that recently I did not work on this module. Let me find time for this.

**Comment by hailangvn** [comment]
> product.image_ids[0].image_main not return raw content, but something like b'34 KB'

`b'34 KB'` was returned because `bin_size` was True in context so [the branch to compute size](https://github.com/odoo/odoo/blob/7017a8bd9d3f79457c5e80f260c0b2d892abee01/odoo/fields.py#L2035) were activated. The `bin_size` was set in order to get image from `product.product` but was brought forward to `base_multi_image.image`.

Thanks @flotho for [the fix](https://github.com/OCA/product-attribute/pull/1099) and @saxomanu for providing details. Just in case we need, below code will work.

```python
            if product.image_ids:
                images = product.image_ids[0].with_context(bin_size=False)
                product.image_variant_1920 = images.image_main
```

**Comment by flotho** [comment]
hi,
great thanks for that, we'll give it a try ASAP
