### ISSUE TITLE
RFC: Product Pricelist Qty Tiers

### ISSUE THREAD

**Issue by lasley** [OCA/product-attribute#185]
I am planning a new module to allow easy product pricing for tiered qty. This is technically possible using a Min Quantity, but the items still have to be priced individually.

In order to save some brainpower and keystrokes, I am thinking to add a price computation type to pricelists called "Tiered Price". It will mimic the operation of the "Fix Price" computation, except that the price will automatically be divided by the "Min Quantity" and apply appropriate rounding.

Following is an example:
- $5.00 for 30 units of X
  - 5/30 = .166666667 per unit with a min qty of 30 & rounding method of 0.01
- $7.00 for 60 units of X
  - 7/60 = .116666667 per unit with a min qty of 60 & rounding method of 0.01

Anyone have thoughts on this, or strategies/modules I am missing?

**Comment by pedrobaeza** [comment]
Yeah, it seems something reasonable that you can do hiding some fields and computing them on background

**Comment by gdgellatly** [comment]
@lasley Lets just hope your min quantity isn't 0.00 (or less than 1 might want checking too).  I'd say their are some small issues to consider with this approach.  Your quantity and price become codependent so in fact future updates become harder.  Consider your example $5.00 for 30 units of X.  Now you decide that actually it should be 50 units as min quantity.  Edit the form you must edit both quantity and price (basically the reverse of the math you just did, so you save day 1, because actually you already precalculated the prices, but day 101, and there is a price rise, you are still recalculating everything, whether in Odoo or otherwise and day 201 recalculating everything again when there is a quantity change).

Another issue you will need to deal with is rounding, say you decide on 3 for $10.00.  You'll get $9.99 each time.  Don't know how you deal with that, but I think it is a bit user confusing to enter a pricelist of 3 for 10, and get 9.99, but from your detail, I think that is what you have handled, just not sure how that ties in with price_get functions, although I'm sure you've looked if proposing it.

However here is one alternative approach that saves brainpower at least.
https://github.com/OCA/web/tree/10.0/web_widget_float_formula - just enter your maths directly in the field.

Not that I don't think your case is valid or otherwise, just that I was here to raise an RFC myself and thought I'd comment

**Comment by lasley** [comment]
@gdgellatly - I share your concerns, particularly in the rounding. AFAIK the Odoo solution to price rounding is to also utilize the surcharge to make up the difference. Obviously this is still at the unit level, so that doesn't help us much.

I didn't think about the updates, but you're correct in that regard as well. 

We upgraded `web_widget_float_formula` to 9.0 with this intent, but the customer was not happy with the solution and would like something that minimum wage employees can handle - I keep receiving the statement "Magento does it". Unfortunately I agree with them on this aspect though, so now it's a matter of conquering it from an engineering perspective.

I was hoping this wouldn't be the case, but it seems that something this simple may not work. It seems the real solution is going to be to inject into the `_price_rule_get_multi` (v9) & `_compute_price_rule` (v10), but that's some nasty business right there. To the drawing board, it seems 😦

**Comment by gdgellatly** [comment]
I've just finished a big v7 effort of applying tax rounding by supplier. If
you look at how v7 and maybe later versions handles round per line vs round
globally it might show you an easier path to handle rounding.

**Comment by pedrobaeza** [comment]
Although the rounding problem is there, it means a step on usability, so maybe it's worth to do it anyway. Look at the workaround we made for a similar problem with prices on packages: https://github.com/OCA/sale-workflow/blob/a0784df06c75325fd717c2f3194252aee9c9e09a/sale_packaging_price/models/product.py#L37

**Comment by citruscorp** [comment]
I'm having a headache with the price list for shopping. It exists in Odoo 9? Until version 8 was easy to work with it. They help me with that?

**Comment by lasley** [comment]
Closing to track in PR #224

**Comment by jholze** [comment]
@pedrobaeza Already closed, but i have one question. What is the best way, to use the configurations of packages on a product for tier price handling ? eg. i have a package of 25 coins and for this i want to define a tier price within a pricelist. Thanks, Jens

**Comment by pedrobaeza** [comment]
The module I mentioned (sale_packaging_price) only allows a direct price, but with no pricelists I'm afraid. You can extend that module for adding support for pricelists, which is going to be a bit weird, or directly add packaging support for pricelists, but the pricelist methods are also not very inheritable, so you have a hard stick here.
