### ISSUE TITLE
RFC: Product Storage Instructions

### ISSUE THREAD

**Issue by lasley** [OCA/product-attribute#205]
We created a [module in vertical-medical that provides a concept of storage instructions for medicaments (products)](https://github.com/laslabs/vertical-medical/tree/release/10.0/medical_medicament_storage).

The module is rudimentary at this point, simply providing a M2M on to relate storage instructions to specific products. 

In our v10 iteration we are planning to add a glue module for `stock`, which would add a concept of the storage possibilities of specific warehouse/bins. 

In the existing module, we are also looking into a concept of storage time as part of the instructions, as well as a field allowing abstract validation (similar to [`partner_identification`](https://github.com/OCA/partner-contact/blob/10.0/partner_identification/models/res_partner_id_category.py#L39)). 

Our medicaments are `_inherits` of products, so it would be very easy to move this logic up a layer if there is interest. 

Product storage is likely something other industries deal with, so I was seeing if there was any interest in this (or if some other strategies exist) before we go further.

**Comment by pedrobaeza** [comment]
Should we close this?

**Comment by lasley** [comment]
Yup seems like nobody cares. We'll leave it in medical!

**Comment by lukebranch** [comment]
@lasley @pedrobaeza ,

I only just came across this RFC, however I can definitely see how this would be incredibly useful for food service companies, or perhaps chemical manufacturing companies that may have specific storage requirements. I definitely see this module being very useful outside of the scope of the medical vertical.

I currently have a use case for this module with a food & beverage distribution company. They sell a wide range of products ranging from dry-aged beef and wines, through to fruits and vegetables. They could definitely find a use for providing specific instructions and inventory locations for storage.

For example, dry aged beef needs to be stored at a constant ~4°C and around 85% humidity, while different wine varietals and vintages will have different storage requirements. 

In a similar manner if you're selling avocados and bananas, you will have specific storage instructions and requirements for these, perhaps also specifying a stock location that is entirely separate for the two so that they don't interact and spoil.

In my humble opinion, I think this should be re-opened, as the module has a wide number of use cases outside of vertical-medical.

**Comment by lasley** [comment]
@lukebranch - Thanks for the elaboration. This was indeed the use case I was thinking of when I submitted this RFC. Reopening. 

I'll tailor & submit the module upstream at some point soon, but feel free to escalate the process by bringing it over yourself 😄  - https://github.com/LasLabs/vertical-medical/tree/release/10.0/medical_medicament_storage

Medicaments are a direct inherit from product, so changes should be incredibly minimal.

**Comment by lukebranch** [comment]
@lasley,

Thanks for reopening this. I may look into doing this next weekend depending on my schedule.

If I was to make a PR, the module name should be product_storage_instruction right?

**Comment by lasley** [comment]
@lukebranch - Yup I think that's a good name for it. `product_storage` may hit the intent too & be a little more concise.
