### ISSUE TITLE
[RFC] Better smart buttons perfomance on product template form view

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/product-attribute#268]
Hello,

Since version 8, I see a recurrent issue for customers with big database, the native product template form view, with all the smarts button sometimes take a very long time to load. (at least for version 8 and 9)
The problem comes from the computation of fields sales_count, purchase_count and mo_count.

I think it would be greate to have 3 small modules to fix this performance issue for version 10 and I would like the opinion of the community on this.

So far, 3 potential solutions : 
1) Simply replace the native logic by an sql query (nice performance improvement)

2) Store the value of these field, and delay computation (using queue_job). It should work well, but it seems a bit too much, to have to install queue_job module just to improve some performance...

3) A very nice feature to have (but I do not know if it is possible, that's why I ask the Community) would be that Odoo compute the field value, only if the user pass the mouse on the smart button.
Indeed,  most of the time, the user don't need these count information when opening the form view, so it would  a lot better if this information would be computed on demand.

Obivously, the first solution is the easiest.
Feel free to share any idea on the subject!

**Comment by gdgellatly** [comment]
Each of these counts is implemented slightly differently.  (Note I'm looking at V10 here, so maybe not in V8)

e.g putting mo_count into SQL won't yield much benefit as it is already using read_group which is pretty efficient anyway.  Same with sales_count except it is running sale.report view first which will suck I imagine.  purchase_count however does not.  

So for me step 1 - 
make purchase_count on product.product use read_group.
make sale_count behave directly on order_lines and use read_group

step 2 is the efficiency of the product template function.
It may not be needed but options here would be to convert to read group somehow, or it might be direct sql.  I can foresee a problem I have where 1 template can have 20,000 variants.  A list of 80 is potentially 100k products.  Because auto_join is already enabled on product.template and read_group accepts dotted domain notation it might just work. (although I suspect that the double join from another model will still make a big IN)

For me read_group is slightly better than native SQL.  You lose a little performance but get ORM enforcement of things (e.g. active tests, acls).

The other thing to consider, and I don't know this very well is using appropriate @api.depends() on the functions.  All of them are always calculated, and it probably is not needed.

Years ago (v5) we had a similar product problem with pricelists in list view of products.  The solution in the end was to make that column invisible and use a context key to stop computation.  Most similar to your 3.  This code still exists in core today - but doesn't work on new web client so you never see pricelists anymore in product view despite the fact they are there.

Anyway, just thoughts.
