### ISSUE TITLE
Default unit of Measure: weight (kg)

### ISSUE THREAD

**Issue by nagybal** [OCA/product-attribute#273]
Dear All! I would like to request a new feature:

I would like to inventory and manufacture agricultural products. Lets say grain. The products I sell does not have a default weight it varies according the sale order.

My idea for solving this, but correct me if there is a better way: if I set the Unit Of Measure of a product to kg »»» odoo should automatically calculate the weight (kg) of the quoted volume.

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/product-attribute/tree/9.0/product_dimension for a similar thing, but this is something you have to make on your own or pay someone for doing it, because this is not a feature request/wishlist over a module (that can be added in the README), but a new module requirement.
