### ISSUE TITLE
product_sequence causes tests to fail

### ISSUE THREAD

**Issue by gdgellatly** [OCA/product-attribute#77]
@AngelMoya-Domatix 

Product Sequence is causing tests on this repo to fail test.  It sets a static default and then a unique constraint.

Moreover I don't understand quite why it is done this way.  Could we not just use copy=False, default=<get sequence> and remove all the methods entirely?  This would number all existing products automatically and ensure duplicates were given a new number.

**Comment by angelmoya** [comment]
Hi, I'm not author of this code, but:
- with copy = false, you lost original code, maybe you want to maintain part of original code.
- with method write, setting code="/" you can set new code of sequence, this is useful setting codes after module installation.

The test should not fail, because create method update this value. This is the same way sales sequence do it.

**Comment by pedrobaeza** [comment]
This is already fixed, so I close.
